### ISSUE TITLE
Make link error

### ISSUE THREAD

**Issue by KHeeCHO** [ntamas/netctrl#7] opened 2024-01-12 04:32 UTC
Helo i already compiled igraph and i'm trying to compile the netctrl.
In make step, error occured.
I think this is linker error but I don't know how to fix it.
___
`[ 91%] Linking CXX executable netctrl
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o): in function `igraph_i_graphml_attribute_record_destroy':
graphml.c:(.text+0x6c): undefined reference to `xmlFree'
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o): in function `igraph_i_graphml_parser_state_destroy':
graphml.c:(.text+0x2cb): undefined reference to `xmlFree'
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o): in function `igraph_i_graphml_attribute_data_setup.part.0':
graphml.c:(.text+0x70d): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x720): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x736): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x751): undefined reference to `xmlStrndup'
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o): in function `igraph_i_graphml_sax_handler_get_entity':
graphml.c:(.text+0x85d): undefined reference to `xmlGetPredefinedEntity'
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o): in function `igraph_i_graphml_sax_handler_start_element_ns':
graphml.c:(.text+0x1579): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x15e4): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1699): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x16c3): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1732): undefined reference to `xmlStrEqual'
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o):graphml.c:(.text+0x1745): more undefined references to `xmlStrEqual' follow
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o): in function `igraph_i_graphml_sax_handler_start_element_ns':
graphml.c:(.text+0x1760): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x178b): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x17e4): undefined reference to `xmlStrndup'
/usr/bin/ld: graphml.c:(.text+0x17f7): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x1821): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x184d): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1860): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1877): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x188f): undefined reference to `xmlStrndup'
/usr/bin/ld: graphml.c:(.text+0x18a2): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x191b): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1983): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1ab1): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1aeb): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1b3d): undefined reference to `xmlStrndup'
/usr/bin/ld: graphml.c:(.text+0x1b52): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x1c80): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1d2c): undefined reference to `xmlStrndup'
/usr/bin/ld: graphml.c:(.text+0x1d5b): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1d71): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1d84): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1d98): undefined reference to `xmlStrndup'
/usr/bin/ld: graphml.c:(.text+0x1dbb): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1dda): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x1e67): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1eb5): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1ec8): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1f68): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x1f87): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x1fe2): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x21e1): undefined reference to `xmlStrEqual'
/usr/bin/ld: graphml.c:(.text+0x225c): undefined reference to `xmlStrndup'
/usr/bin/ld: graphml.c:(.text+0x226f): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x229b): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x22c1): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x2379): undefined reference to `xmlFree'
/usr/bin/ld: graphml.c:(.text+0x2443): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x2480): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x260f): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x26e1): undefined reference to `xmlStrncmp'
/usr/bin/ld: graphml.c:(.text+0x2893): undefined reference to `xmlStrncmp'
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o):graphml.c:(.text+0x298b): more undefined references to `xmlStrncmp' follow
/usr/bin/ld: /usr/local/lib/libigraph.a(graphml.c.o): in function `igraph_read_graph_graphml':
graphml.c:(.text+0x2c97): undefined reference to `xmlInitParser'
/usr/bin/ld: graphml.c:(.text+0x2f31): undefined reference to `__xmlGenericError'
/usr/bin/ld: graphml.c:(.text+0x2f39): undefined reference to `__xmlGenericErrorContext'
/usr/bin/ld: graphml.c:(.text+0x2f41): undefined reference to `__xmlStructuredError'
/usr/bin/ld: graphml.c:(.text+0x2f4e): undefined reference to `__xmlStructuredErrorContext'
/usr/bin/ld: graphml.c:(.text+0x2f69): undefined reference to `xmlSetGenericErrorFunc'
/usr/bin/ld: graphml.c:(.text+0x2f78): undefined reference to `xmlSetStructuredErrorFunc'
/usr/bin/ld: graphml.c:(.text+0x2f95): undefined reference to `xmlCreatePushParserCtxt'
/usr/bin/ld: graphml.c:(.text+0x2fae): undefined reference to `xmlCtxtUseOptions'
/usr/bin/ld: graphml.c:(.text+0x2fcb): undefined reference to `xmlParseChunk'
/usr/bin/ld: graphml.c:(.text+0x3016): undefined reference to `xmlParseChunk'
/usr/bin/ld: graphml.c:(.text+0x3026): undefined reference to `xmlSetGenericErrorFunc'
/usr/bin/ld: graphml.c:(.text+0x3035): undefined reference to `xmlSetStructuredErrorFunc'
/usr/bin/ld: graphml.c:(.text+0x3042): undefined reference to `xmlFreeParserCtxt'
/usr/bin/ld: graphml.c:(.text+0x304f): undefined reference to `xmlFreeDoc'
/usr/bin/ld: graphml.c:(.text+0x32b4): undefined reference to `xmlFreeParserCtxt'
/usr/bin/ld: graphml.c:(.text+0x32ca): undefined reference to `xmlSetGenericErrorFunc'
/usr/bin/ld: graphml.c:(.text+0x32d9): undefined reference to `xmlSetStructuredErrorFunc'
/usr/bin/ld: /usr/local/lib/libigraph.a(arpack.c.o): in function `igraph_arpack_rssort':
arpack.c:(.text+0x964): undefined reference to `dsortr_'
/usr/bin/ld: /usr/local/lib/libigraph.a(arpack.c.o): in function `igraph_arpack_rnsort':
arpack.c:(.text+0xdc8): undefined reference to `dsortc_'
/usr/bin/ld: /usr/local/lib/libigraph.a(arpack.c.o): in function `igraph_arpack_rssolve':
arpack.c:(.text+0x1656): undefined reference to `dsaupd_'
/usr/bin/ld: arpack.c:(.text+0x16f5): undefined reference to `dseupd_'
/usr/bin/ld: /usr/local/lib/libigraph.a(arpack.c.o): in function `igraph_arpack_rnsolve':
arpack.c:(.text+0x28b6): undefined reference to `dnaupd_'
/usr/bin/ld: arpack.c:(.text+0x36bd): undefined reference to `dneupd_'
collect2: error: ld returned 1 exit status
make[2]: *** [src/ui/CMakeFiles/netctrl.dir/build.make:132: src/ui/netctrl] Error 1
make[1]: *** [CMakeFiles/Makefile2:176: src/ui/CMakeFiles/netctrl.dir/all] Error 2
make: *** [Makefile:156: all] Error 2`
___
These are the errors.
Where i shoud fix it?

**Comment by szhorvat** [comment] 2024-01-12 12:59
@ntamas Shouldn't CMake deal with transitive dependencies automatically for as long as both dependent and dependency are using CMake?

**Comment by szhorvat** [comment] 2024-01-12 13:17
@ntamas I can reproduce this issue if I try to build with a static igraph library. Isn't this project missing `target_link_libraries(netctrl PUBLIC igraph::igraph)`? The code looks like it was written to support pre-CMake versions of igraph, but now 10.3 is required anyway, so you can make use of all CMake features.

**Comment by KHeeCHO** [comment] 2024-01-12 13:25
I'm sorry that I don't know well about CMake.. I just followed the netctrl and igraph installation steps.
Below are the codes I followed. Nothing changed in your compiling steps. 
So could you explain where should I fix for solve this error or how use dynamic library?
```
< in igraph >
cd igraph
mkdir build
cd build
cmake ..
cmake --build .
cmake --build . --target check
cmake --install .

< in netctrl >
git submodule update --init
mkdir build
cd build
cmake ..
make
```

**Comment by szhorvat** [comment] 2024-01-12 14:02
@KHeeCHO When you are configuring igraph, replace `cmake ..` with `cmake .. -DBUILD_SHARED_LIBS=ON`.

**Comment by ntamas** [comment] 2024-01-12 19:17
> The code looks like it was written to support pre-CMake versions of igraph

Most likely it was, its last significant update was before igraph switched to using CMake as its own build system and started providing CMake targets that could be imported by other CMake projects.

Anyhow, the CMake build system of `netctrl` deserves an upgrade so I'll try to sort these out.

**Comment by ntamas** [comment] 2024-01-12 19:40
I've committed a few quick changes now, not sure if all corner cases are covered (maybe not), but the instructions seem to work for me on my machine when I start from scratch.

**Comment by KHeeCHO** [comment] 2024-01-13 03:18
I appreciate you fixing the code. It seems done.
Can I ignore any errors during the build?
```
/home/Jhard/khcho/netctrl/vendor/igraphpp/include/igraph/cpp/graph.h:64:16: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   64 |     Graph(std::auto_ptr<igraph_t> graph) throw() : m_pGraph(graph.release()) {
      |                ^~~~~~~~
In file included from /usr/include/c++/9/memory:80,
                 from /home/Jhard/khcho/netctrl/vendor/igraphpp/include/igraph/cpp/graph.h:7,
                 from /home/Jhard/khcho/netctrl/vendor/igraphpp/include/igraph/cpp/io/edgelist.h:6,
                 from /home/Jhard/khcho/netctrl/vendor/igraphpp/include/igraph/cpp/io.h:6,
                 from /home/Jhard/khcho/netctrl/src/ui/graph_util.cpp:5:
/usr/include/c++/9/bits/unique_ptr.h:53:28: note: declared here
   53 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
[100%] Linking CXX executable netctrl
[100%] Built target netctrl
```

**Comment by ntamas** [comment] 2024-01-13 10:09
This is harmless; `auto_ptr` is deprecated in C++ but it still works. I'll eventually switch to a `unique_ptr` but you shouldn't need to worry about this.

**Comment by ntamas** [comment] 2024-01-13 11:05
I've migrated the code to `std::unique_ptr<>` so it should now compile without warnings.

**Closed by ntamas** 2024-01-13 11:05 UTC
